version: '3.4'

services:
  dii_theatermanagement_bff:
    image: ${DOCKER_REGISTRY-}diitheatermanagementbff
    build:
      context: .
      dockerfile: src/Dii_TheaterManagement_Bff/Dockerfile
  dii_theatermanagement_bff-dapr:
     image: "daprio/daprd:latest"
     command: [ "./daprd", "-app-id", "diitheatermanagementbff", "-app-port", "80" ]
     depends_on:
        - dii_theatermanagement_bff
     network_mode: "service:dii_theatermanagement_bff" 

  providers.fake:
    image: ${DOCKER_REGISTRY-}providersfake
    build:
      context: .
      dockerfile: fake/Providers.Fake/Dockerfile
  dii_orderingsvc-dapr:
     image: "daprio/daprd:latest"
     command: [ "./daprd", "-app-id", "diiorderingsvc", "-app-port", "80", "-metrics-port", "9090","-dapr-grpc-port", "50001","-dapr-http-port", "3501" ]
     depends_on:
        - providers.fake
     network_mode: "service:providers.fake" 
   
  dii_moviecatalogsvc-dapr:
     image: "daprio/daprd:latest"
     command: [ "./daprd", "-app-id", "diimoviecatalogsvc", "-app-port", "80", "-metrics-port", "9092","-dapr-grpc-port", "50002","-dapr-http-port", "3502" ]
     depends_on:
        - providers.fake
     network_mode:  "service:providers.fake"

